---
- name: deploy lamp stack
  hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/vagrant/latest.sh
        dest: /home/vagrant/latest.sh
        owner: root
        group: root
        mode: '0755'

    - name: install lamp stack and laravel
      script: /home/vagrant/latest.sh
      
     
